"use client";

import Link from "next/link";
import { ArrowRight, BellRing, CheckCircle2, CircleAlert, TrendingDown, TrendingUp } from "lucide-react";
import { useWorkspace } from "@/lib/store";
import { money, pct } from "@/lib/format";
import { Chip, StatusBadge } from "@/components/ui/Bits";
import { PageHeader, PageShell } from "@/components/shell/PageHeader";

export default function AlertsPage() {
  const { brand, current, comparison } = useWorkspace();
  const profitDelta = current.netProfit - comparison.netProfit;
  const items = [
    { tone: current.netMarginPct < 0 ? "critical" : "warning", title: current.netMarginPct < 0 ? "Net margin is below break-even" : "Margin is holding", body: `${pct(current.netMarginPct, 1)} net margin in ${current.label}; the break-even point is 0%.`, action: "Open P&L", href: "/statement" },
    { tone: current.cac > comparison.cac ? "warning" : "good", title: current.cac > comparison.cac ? "Acquisition cost is rising" : "Acquisition cost is improving", body: `CAC is ${money(current.cac)} per order against ${money(comparison.cac)} in ${comparison.label}.`, action: "Open forecast", href: "/forecast" },
    { tone: profitDelta < 0 ? "critical" : "good", title: profitDelta < 0 ? "Profit moved down" : "Profit moved up", body: `${money(Math.abs(profitDelta))} ${profitDelta < 0 ? "lost" : "added"} versus ${comparison.label}.`, action: "Read detail report", href: "/scrum" },
  ] as const;
  return <PageShell><PageHeader eyebrow={<><Chip tone="brand">{brand.name}</Chip><Chip tone="neutral">Monitoring</Chip></>} title="Alerts & insights" subtitle="The ranked operating signals from Nira. Every alert points to a next action, not just a red number." actions={<Link href="/drr" className="inline-flex items-center gap-2 rounded-lg bg-brand px-3.5 py-2.5 text-[13px] font-semibold text-[#173f28] hover:bg-brand-hover">Open monitor <ArrowRight size={15} /></Link>} /><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="card p-4"><p className="label-xs">Open signals</p><p className="figure-lg mt-2 text-[26px]">{items.length}</p><p className="mt-1 text-[12px] text-ink-3">Prioritized for {brand.name}</p></div><div className="card p-4"><p className="label-xs">Critical</p><p className="figure-lg mt-2 text-[26px] text-critical-ink">{items.filter((item) => item.tone === "critical").length}</p><p className="mt-1 text-[12px] text-ink-3">Needs a decision this cycle</p></div><div className="card p-4"><p className="label-xs">Last synced</p><p className="mt-2 text-[17px] font-semibold text-ink">12 minutes ago</p><p className="mt-1 text-[12px] text-ink-3">Local model preview</p></div></div><div className="mt-6 space-y-3">{items.map((item) => <div key={item.title} className="card flex flex-wrap items-center gap-4 p-4"><span className={`grid size-10 place-items-center rounded-full ${item.tone === "critical" ? "bg-critical-soft text-critical-ink" : item.tone === "warning" ? "bg-warning-soft text-warning-ink" : "bg-good-soft text-good-ink"}`}>{item.tone === "critical" ? <CircleAlert size={18} /> : item.tone === "warning" ? <BellRing size={18} /> : <CheckCircle2 size={18} />}</span><div className="min-w-[220px] flex-1"><div className="flex items-center gap-2"><h2 className="text-[14px] font-semibold text-ink">{item.title}</h2><StatusBadge status={item.tone === "critical" ? "critical" : item.tone === "warning" ? "warning" : "good"} label={item.tone === "good" ? "Opportunity" : item.tone === "critical" ? "Critical" : "Review"} /></div><p className="mt-1 text-[12.5px] text-ink-3">{item.body}</p></div><Link href={item.href} className="inline-flex items-center gap-1.5 text-[12.5px] font-semibold text-brand-ink hover:underline">{item.action} <ArrowRight size={14} /></Link></div>)}</div><div className="mt-6 rounded-xl border border-line bg-surface-2 px-4 py-3 text-[12px] text-ink-3">Nira’s original alert engine also supports custom thresholds and data-anomaly flags. Those rules will read from the Google Sheets gateway when live rows are connected.</div></PageShell>;
}